### ISSUE TITLE
Server connection could not be established

### ISSUE THREAD

**Issue by hraztan** [500Foods/TMS-XData-TemplateDemoData#6]
Hi

I can run the project fine on my development PC. When I try to run it on another device on my network by using my developer PC's IP, even though it's loading the initial login page successfully, when I try to login it's giving me the following exception:

"Server connection could not be established"

Please, advise

**Comment by 500Foods** [comment]
Hi there...  Thanks for taking this out for a spin. When running this along with its companion, the [Template Demo](https://github.com/500Foods/TMS-WEB-Core-TemplateDemo), locally in a dev environment, the reference to XData is assumed to be something like http://localhost:12345.  So when you connect to it from outside of that system, this won't work out so well.

To address this, you can create a configuration JSON file for the Template Demo project (not this one) where you can specify the IP and port to use for the XData server (this respository's server, in other words).  So that when you load that page on another remote system, it knows where to look.  There is a brief section on Deployment in that repository that describes how to set this up and test it.

Note also that if you're accessing this XData server remotely, that you may have to open up a port on the Windows Firewall (or any other similar product you might be using) to allow access to it.

**Comment by hraztan** [comment]
Hi. Thank you for your answer. I already saw the documentation and created the configuration JSON file. It's working fine now. I had just assumed that the web server was the one connecting to the XData Server, so the localhost would be fine. Obviously, it is the client connecting to the XData server.
